# try:
#     result = 5 / 0
#     print(result)
# except:
#     print("Something went wrong")
# exception handling:
# try:
#     result = 5 / 1
#     print(result)
# except ZeroDivisionError:
#     print("You can't divide by zero")
# except Exception as error:
#     print(f"unexpected error {error}")

# else:
# try:
#     result=20/2
#     print(result)
# except zeroDivisonError:
#     print("ZeroDivisionError")
# else:
#     print("divison successfully")

# try:
#     print(12)
# except:
#     print('error')
# else:
#     print('no error')
# finally:
#     print('always')

# try:
#     print("python")
# except TypeError:
#     print('TypeError')
# except ValueError:
#     print('ValueError')



